services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adacecam_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - adacecam_network
    depends_on:
      - mysql
      - redis

  webserver:
    image: nginx:alpine
    container_name: adacecam_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - adacecam_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: adacecam_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: adacecam_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: adacecam_user
      MYSQL_PASSWORD: adacecam_password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - adacecam_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: adacecam_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    networks:
      - adacecam_network
    depends_on:
      - mysql

  redis:
    image: redis:7-alpine
    container_name: adacecam_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - adacecam_network

  mailhog:
    image: mailhog/mailhog
    container_name: adacecam_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - adacecam_network

networks:
  adacecam_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
